### PR TITLE
Move `rescript/tools` to OCaml

### PR DESCRIPTION
**Pull request by aspeddro**
- Move `rescript/tools` to OCaml Code, `tools/src/Cli.res` to `tools/bin/main.ml`
- Now `analysis` is a library consumed by `tools`. The `rescript-editor-analysis` binary is still built, see `analysis/bin/main.ml`

Ideally, we should divide packages by platform (https://github.com/rescript-lang/rescript-compiler/issues/6183), but this change seeks to reduce node bin wrapper

Everything works as a monorepo:
- `dune build` compile `analysis` and `tools`. `analysis` is a dep of `tools`.
- The switch is created in the root, there is no need to enter the `analysis` directory

I think this improves the development experience.

### CODE REVIEW

**Comment by aspeddro** [comment]
@zth If you are interested I can resolve the conflicts

**Comment by zth** [comment]
@aspeddro let's do it!

**Comment by zth** [comment]
@aspeddro sorry, another merge needed... 😬 

I tried the branch and it seems to work! I wasn't able to get ocamlformat working though (but I didn't try that much, just noticed it's broken for me). Do you have it working?

**Comment by aspeddro** [comment]
I removed `ocamlformat` dep https://github.com/rescript-lang/rescript-vscode/pull/855/commits/bff2928d79d4fb70dcf6aea220b5195f9247d19f. Don´t make sense since we don't run format check on CI.

You should install on switch `opam install ocamlformat`

CONTRIBUTING.md updated https://github.com/rescript-lang/rescript-vscode/pull/855/commits/546b7ca49728d5b61e193ada833dfad20cbe7201

**Pull request merged**
