### PR TITLE
Support rescript.json

### PR DESCRIPTION
**Pull request by fhammerschmidt**
Gave it a try, not sure if it is the right approach though.

### CODE REVIEW

**Comment by zth** [comment]
Looks good to me! And you tested that everything worked with both rescript.json and bsconfig.json, including the code analyzer etc?

cc @cristianoc

**Comment by cristianoc** [comment]
> Looks good to me! And you tested that everything worked with both rescript.json and bsconfig.json, including the code analyzer etc?
> 
> cc @cristianoc

Same comment. Looks good if everything is tested.

**Comment by fhammerschmidt** [comment]
Now I tested it and of course found some missing checks. Should work now for both monorepos and normal ones.

**Comment by cknitt** [comment]
Tested against a big monorepo project of ours, worked fine, even with rescript.json and bsconfig.json mixed across packages.

**Comment by zth** [comment]
Excellent! Merging and we can fix in follow ups.

**Pull request merged**
