### PR TITLE
Highlight tagged template fn as fn

### PR DESCRIPTION
**Pull request by zth**
This highlights tagged template functions used as a function.

Before:
image

After:
image

### CODE REVIEW

**Comment by DZakh** [comment]
@zth @fhammerschmidt I wonder how correct it is to highlight it as a function, when we usually treat functions as regular variables in other places

image

**Comment by zth** [comment]
Other variables we don't know whether they're functions or not, because we'd need to do potentially expensive lookups. This one we always know is a function because only a function can be used as a tagged template literal function.

**Comment by DZakh** [comment]
I'm just thinking that it might be better to be consistent in not highlighting functions

**Comment by zth** [comment]
I don't think that's a problem, this is also a pretty isolated context from other functions so it's fine.

**Comment by DZakh** [comment]
> Other variables we don't know whether they're functions or not, because we'd need to do potentially expensive lookups.

By the way, do you know how TS does it?

**Comment by zth** [comment]
> > Other variables we don't know whether they're functions or not, because we'd need to do potentially expensive lookups.
> 
> By the way, do you know how TS does it?

They use semantic highlighting, and look up the actual type definition for each identifier to see if it's a function.

We could do the same, but we'd need to benchmark it because it _might_ be taxing on performance. So far we haven't used any of the type information for highlighting (IIRC). But we could probably try it out as an experiment, should be easy enough. Would be good to have benchmarks for it.

**Comment by DZakh** [comment]
I see. But I actually like functions of the same color as variables 😁

**Pull request merged**
