### PR TITLE
Upgrade `ocamlformat@0.26.1` 

### PR DESCRIPTION
**Pull request by aspeddro**
This allows using latest `ocaml-lsp-server`

### CODE REVIEW

**Comment by zth** [comment]
Is upgrading the LSP blocked because of an older ocaml-format version? Seriously?

**Comment by cknitt** [comment]
Yes, see also https://github.com/rescript-lang/rescript-compiler/pull/6360.

We cannot upgrade the version in the compiler repo though because we also install and run it in CI for format checks, and it is not in the OPAM repo used for Windows...

I think we should avoid using a different version in the rescript-vscode repo than in the compiler repo.

**Comment by zth** [comment]
Right, got it. Just perplexed that upgrading a _formatter_ (implicitly meaning potentially dealing with a bunch of reformatting conflicts for all outstanding branches) is allowed to block upgrading the LSP itself.

**Comment by aspeddro** [comment]
Ready for merge

**Pull request closed without merging**
