### PR TITLE
Publish LSP to npm

### PR DESCRIPTION
**Pull request by aspeddro**
- Publish a binary to npm as `rescriptls`. Support two channels `stdio` and `node-ipc`
- VSCode client keeps using `node-ipc` channel

Related #354

### CODE REVIEW

**Comment by zth** [comment]
Great stuff! 

One thing I'd like to mull over a bit before going this route is that there might be a separate case for publishing just the analysis binary to npm, by itself. That would be because the analysis binary might in the future contain more general tooling, not just stuff for powering the LSP. Doc extraction is one example where it's possible that's the easiest way of distributing it.

This package will have the analysis bin too of course. So maybe there's a way to name this (and expose the analysis bin separately) so that they can be exposed via the same package, without it being fantastically confusing.. Let me think a bit. Any feedback welcome.

**Comment by cristianoc** [comment]
Perhaps only expose the part of the analysis binary which is for public consumption. Whiteout even leaking the existence of the binary (helps keeping freedom to move stuff between binary and ts).

**Comment by aspeddro** [comment]
If I understand correctly, as reported by users the main problem is that we don't publish an LSP like OCaml does to facilitate the setup in several editors. Just publishing the analysis binary does not resolve the reported issue.

> yes accessing lsp server and related binaries each time when changing machine that doesn't have it mean setting up $PATH or changing editor configuration file (in this case Helix) over again. npm package definitely help.
[Comment](https://github.com/rescript-lang/rescript-vscode/issues/354#issuecomment-1207222732)

One idea is to do what [`rust-analyzer`](https://github.com/rust-lang/rust-analyzer/blob/a6603fc21d50b3386a488c96225b2d1fd492e533/crates/rust-analyzer/src/cli/flags.rs#L9-L117) does. We publish a single binary with subcommands.

- `rescript-toolchain lsp [args]` - Start LSP
- `rescript-toolchain analysis [args]` - Call OCaml `analysis binary` commands

**Comment by aspeddro** [comment]
Ready for review.

**Comment by aspeddro** [comment]
The first version should be `0.0.1` or `1.20`?

**Review by zth — APPROVED** [review]
Awesome! I think `1.20.0` for the version is right, it's nice to have the same as the actual extension.

Fantastic to get this out.

**Pull request merged**
