### PR TITLE
Redo pr 649

### PR DESCRIPTION
**Pull request by cristianoc**

### CODE REVIEW

**Comment by cristianoc** [comment]
@aspeddro this should work, only needs cleaning up the changelog.

**Comment by aspeddro** [comment]
I thought it was fixed in master. Thanks @cristianoc.

**Comment by cristianoc** [comment]
These are 2 different issues:
1 references to elements defined in interface files
2 references from implementation files which also happen to have interface files

**Comment by cristianoc** [comment]
1 in master
2 here

**Comment by cristianoc** [comment]
All done now.

**Pull request merged**
