### PR TITLE
Add markdown code block syntax highlight support

### PR DESCRIPTION
**Pull request by wangbinyq**

### CODE REVIEW

**Comment by chenglou** [comment]
Hey, thanks! Though is this the idiomatic way of doing it? It seems typescript's grammar repo doesn't have such thing?

**Comment by wangbinyq** [comment]
I rewrite the file from the [vscode-reasonml](https://github.com/reasonml-editor/vscode-reasonml) repo, just some minor changes.

**Comment by fhammerschmidt** [comment]
@zth can we get semantic highlighting in markdown blocks as well?

**Comment by zth** [comment]
@fhammerschmidt I'm not sure. Does TS do it?

**Comment by aspeddro** [comment]
I was looking for how vscode apply syntax highlighting in markdown. It doesn't use semantic highlighting just TexMate grammar.

[Here](https://github.com/microsoft/vscode/blob/main/extensions/markdown-basics/package.json#L33-L86) are supported languages.

**Comment by fhammerschmidt** [comment]
Having at least a bit of highlighting would already be nice.
Currently it is just all the same color.

image

**Comment by zth** [comment]
I'm thinking we should merge this as is. I agree that some highlighting is better than none. Ok with you @cristianoc ?

Side note: There's more interesting things we can do eventually to better support md, like formatting code inside of ReScript md blocks.

**Pull request merged**
