### PR TITLE
Add vsce pre-release step to CI

### PR DESCRIPTION
**Pull request by fhammerschmidt**
~~This is a first step to having automatic pre-releases published in the VSCode marketplace.~~

Somebody with access rights needs to create a `secrets` environment in this GitHub repository and add (one of) the ReScript team's [Personal Access Token (PAT)](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token) as an environment variable, named  `MARKETPLACE_TOKEN `.

EDIT: 
This PR is basically done, but there is probably still room for some fine-tuning. As mentioned above, someone with write access needs to provide the token(s). 

Also the `chenglou92.rescript-vscode` needs to be updated to whatever will be the VSCode publisher name afterwards.

### CODE REVIEW

**Comment by zth** [comment]
Awesome! How does versioning work here? I'm not fully read up on pre releases in the marketplace.

**Comment by fhammerschmidt** [comment]
Well, I did not account for that yet, but I guess we also need to have version numbers for pre-releases, separated from main releases. What rust-analyzer does is basically what is also [suggested by the docs](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions), i.e. having a version where the minor part is an odd number that is always one higher than the minor part of the main release.

E.g. the pre-release version for rescript-vscode now would be `1.3.1` as the latest release is currently `1.2.1` and so on.

Something is needed to increment the patch number automatically [This can be done with vsce as well](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#autoincrementing-the-extension-version).
Otherwise we will always overwrite the current version and users will not be notified for updates.

**Comment by fhammerschmidt** [comment]
Here is a chart with the full workflow for a merge into master (not for a PR build):

```mermaid
flowchart TD
A[pull request gets merged into master branch]
A-->B[build analysis binaries]

subgraph ci [ ]
subgraph textNode1 [ci.yml]
style textNode1 fill:none,stroke:none
end
B-->C[fetch current highest version - 1.3.0]
C-->D[bump-version.js script increments version - 1.4.1]
D-->E[vsce package with bumped minor - 1.4.1]
E-->F[vsce prepublish with bumped minor - 1.4.1]
E-->G[add packaged version to releases page - Latest master]
end

F & G -->  I[Done]
```

**Comment by fhammerschmidt** [comment]
@zth @cristianoc feel free to review and roast me!

**Comment by fhammerschmidt** [comment]
Yes, you can create a branch and add it's name to the push branches in ci.yml.

There are now two tokens at play here:
* `GITHUB_TOKEN` this one should be provided by GitHub automatically.
* `MARKETPLACE_TOKEN`: This one is still needed for the actual publish to happen. See [initial comment](https://github.com/rescript-lang/rescript-vscode/pull/399#issue-1217935941).

**Comment by zth** [comment]
Can we test this in the current namespace we have? I'm thinking it'd be good to do that, get one final release out, and then move to our new real Marketplace ReScript org. Would that essentially be merging this and ensuring the marketplace token is available?

**Comment by cristianoc** [comment]
We're a little behind with new releases. Don't know if this has to complete before a new release is done.

**Comment by fhammerschmidt** [comment]
It is completely independent of main releases, which will still be done manually after this PR gets merged.

**Comment by fhammerschmidt** [comment]
Ad 1.: Yes, but first add the token and then merge it, the next master build should automatically publish a pre-release then.

Ad 2.: 
No, the first case is special. We do not have a pre-release published yet, so VSCE will give us `1.3.0` as the latest published version (pre-releases and releases are lumped together in the versions array) . If you give the `bump-version` script a `1.3.0` it yields `1.4.0` which is correct because that one is not in use yet.

In a subsequent push to master, it will retrieve the most recent version again which would then be the pre-published `1.4.0`, so it will bump to `1.4.1`. The above diagram was slightly wrong, but I corrected it now to reflect the publish step after the initial one. 

Ad 3.: The only thing with regards to main releases is that you need to keep in mind that we would be forced to use the odd minor numbers for them, while using the even ones for pre-releases, e.g.

| Release  | Pre-Release |
| ------------- | ------------- |
| 1.3.0  | 1.4.0  |
| 1.3.0  | 1.4.1  |
| 1.3.0  | 1.4.2  |
| 1.3.0  | 1.4.3  |
| 1.3.1  | 1.4.4  |
| 1.5.0  | 1.6.0  |

The bump-version script actually missed the case when there is a higher minor version in package.json, but not in the marketplace, I fixed that now.

**Comment by zth** [comment]
@fhammerschmidt no that's great! I'm going to get the token sorted and we can merge this.

**Comment by fhammerschmidt** [comment]
@zth I really think it is inconsistent when we start from 1.3.0. Maybe we can first release a 1.4.0 and merge it afterwards?

**Comment by zth** [comment]
@fhammerschmidt sorry, missed the last part of your message. Yes, I agree. Let's get a `1.4.0` out first, and then merge this after.

**Comment by zth** [comment]
@fhammerschmidt setting up the token + merging this tomorrow.

**Comment by zth** [comment]
Turns out I don't have permissions to produce that marketplace token. Pinging @ryyppy who might have more luck in that regard.

**Comment by ryyppy** [comment]
@fhammerschmidt just created a `MARKETPLACE_TOKEN` and created the Action secret for this repository.

**Comment by fhammerschmidt** [comment]
Cool. 

@zth If you want I can create another PR just to test if the token works in CI (using https://fig.io/manual/vsce/verify-pat).

**Comment by zth** [comment]
> Cool.
> 
> @zth If you want I can create another PR just to test if the token works in CI (using https://fig.io/manual/vsce/verify-pat).

Go for it!

**Comment by zth** [comment]
@fhammerschmidt what's the status now, are we waiting for @ryyppy to reply in the other PR?

**Comment by fhammerschmidt** [comment]
As you like. I believe he was or is still sick and was not able to answer.

**Comment by fhammerschmidt** [comment]
So, to clarify: if you want to be sure the token is valid, you should wait for Patrick. Otherwise feel free to pull the trigger.

**Comment by zth** [comment]
@fhammerschmidt mind rebasing on master again? Inclined to merge this after that and we'll just try to fix whatever comes up if things don't work like we want to.

**Comment by fhammerschmidt** [comment]
I am currently on mobile. Could do it in a couple of hours.

**Comment by fhammerschmidt** [comment]
Rebased!

**Comment by zth** [comment]
Fire in the hole!

**Pull request merged**
