### PR TITLE
Add `await` as keyword

### PR DESCRIPTION
**Pull request by IwanKaramazow**

### CODE REVIEW

**Review by zth — APPROVED** [review]
👍

**Comment by cristianoc** [comment]
We can add this already now.

**Comment by cristianoc** [comment]
And extend semantic highlighting.

**Comment by zth** [comment]
Maybe we could make `async` a regular textmate highlight? Wouldn't it always be `async (`?

**Comment by cristianoc** [comment]
> Maybe we could make `async` a regular textmate highlight? Wouldn't it always be `async (`?

That's the parser's job. Better not make assumptions, which might change, on what may or may not follow `async`. Unless the grammar is best effort and semantic highlighting has the final say.

**Comment by IwanKaramazow** [comment]
> Maybe we could make `async` a regular textmate highlight? Wouldn't it always be `async (`?

It's unfortunately trickier, could be a normal function call:
```rescript
@val
external setTimeout: (unit => unit, int) => unit = "setTimeout"

let async = () => {
  setTimeout(() => {
    Js.log("async")
  }, 5000)
}

let f = async (          )
```

Arrow functions (both async and normal) introduce a lot of complexity for little gain.

**Pull request merged**
