### PR TITLE
Add macos-arm binary

### PR DESCRIPTION
**Pull request by cknitt**
This adds the rescript-editor-analysis.exe binary for macOS ARM.

### CODE REVIEW

**Review by cristianoc — APPROVED** [review]
Sweet.

**Comment by cristianoc** [comment]
It's not packaged yet right?

**Comment by cknitt** [comment]
Still WIP/testing at the moment.

**Comment by cknitt** [comment]
Tested with the resulting VSIX, seems to work fine now. 😄

**Review by cristianoc — APPROVED** [review]

**Pull request merged**
