### PR TITLE
Fix formatting textedit range

### LINKED ISSUE #259: Unexpected formatter behavior when there are redundant lines
try to format this
```rescript
let a =










  2
```

file changes to:
```rescript
let a = 2

  2
```

### PR DESCRIPTION
**Pull request by amiralies**
Closes #259

### CODE REVIEW

**Comment by amiralies** [comment]
Trivial fix would be using file content's length (before formatting)

**Comment by cristianoc** [comment]
This also seems to fix:
```ts
              end: { line: max+1, character: max },
```

**Comment by amiralies** [comment]
yeah we can use file length. but note that we should use current text length instead of formatted text length.
(think of  TextEdit as a range you're selected in editor and gonna replace that with newText)

**Comment by cristianoc** [comment]
A fixed large number would also work I guess, thought it looks less clean.

**Comment by cristianoc** [comment]
As long as it's simple and it works, no preferences.

**Comment by cristianoc** [comment]
Actually let me double check: are we taking about formatting the whole file?
Or is the idea to allow formatting a smaller part in isolation.

**Comment by amiralies** [comment]
We just support formatting the whole file.
But lsp doesn't have a method of replacing the whole file text. it accepts a list of edits.
what we need is return a single `TextEdit` in a list with a `range` covering the whole file (before formatting) and `newText` which is the formatted result.

**Comment by amiralies** [comment]
I've updated to use current file's length as max range. I guess it's okay for now. we can change it later if we faced performance issues or other problems,

**Comment by cristianoc** [comment]
Great

**Pull request merged**
