### PR TITLE
Incremental typechecking

### PR DESCRIPTION
**Pull request by zth**
A first, experimental and opt in version of incremental typechecking. Still things to iron out, but should be enough to get some testing going.

Activate in the settings dialogue `(beta/experimental) Enable incremental type checking.`.

https://github.com/rescript-lang/rescript-vscode/assets/1457626/2353cfb8-561c-4a53-8151-1b2b4608f242

### CODE REVIEW

**Review by cristianoc — APPROVED** [review]
Magic

**Comment by Mng12345** [comment]
This is amazing!

**Comment by Mng12345** [comment]
@zth Hi, did you forget to publish the extension to vscode extension market?

**Comment by fhammerschmidt** [comment]
@Mng12345 Maybe you forgot to enable it in settings? Works for me with the latest pre-release version (v1.43.4)
`"rescript.settings.incrementalTypechecking.enabled": true`

**Comment by Mng12345** [comment]
It works now after the extension was updated 20minutes before.
image

**Pull request merged**
