### PR TITLE
Fix URL scheme for code actions

### PR DESCRIPTION
**Pull request by aspeddro**
Neovim client raise an error because server does not return an URI scheme `file:///`

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/uri.lua:107: URI must contain a scheme: /home/pedro/Desktop/learning-rescript/src/let_binding.res
stack traceback:
        [C]: in function 'assert'
        /usr/share/nvim/runtime/lua/vim/uri.lua:107: in function 'uri_to_fname'
        /usr/share/nvim/runtime/lua/vim/uri.lua:128: in function 'uri_to_bufnr'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:570: in function 'apply_text_document_edit'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:828: in function 'apply_workspace_edit'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:803: in function 'apply_action'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:857: in function 'on_choice'
        /usr/share/nvim/runtime/lua/vim/ui.lua:54: in function 'select'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:868: in function 'on_code_action_results'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:886: in function 'callback'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1952: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### CODE REVIEW

**Comment by zth** [comment]
@aspeddro did you test this in VSCode as well?

**Comment by aspeddro** [comment]
Yes, everything working.

**Comment by zth** [comment]
Looks like there's still conflicts. Happy to merge after they're fixed.

**Comment by aspeddro** [comment]
Conflicts resolved.

**Pull request merged**
