### PR TITLE
Correct ReScript bindings for signature details

### PR DESCRIPTION
**Pull request by nojaf**
After trying this in my own project, I noticed that the bindings were not 100% accurate.

### CODE REVIEW

**Comment by zth** [comment]
Did you try this fix in your project?

**Comment by nojaf** [comment]
Yep!

**Comment by nojaf** [comment]
Thanks, would appreciate a release when you find the time.

**Comment by zth** [comment]
It's released already.

**Comment by nojaf** [comment]
I'm talking about `0.6.6`

image

https://www.npmjs.com/package/@rescript/tools?activeTab=versions

**Comment by zth** [comment]
So am I:

image

**Comment by nojaf** [comment]
Takes a while to reflect on the website it seems:

image


Thanks!

**Pull request merged**
