### PR TITLE
Show Docstrings for completion items

### LINKED ISSUE #469: Show docs for file modules on type hint
Related to module level docstring support (see [syntax issue](https://github.com/rescript-lang/syntax/issues/579)).

When e.g. type hinting `Belt_Array`, I get `file module` as docs:
image

Ideally, it would show the module level docs instead.

### PR DESCRIPTION
**Pull request by aspeddro**
Neovim:
image

VSCode:
image

Related #469
Close #469

### CODE REVIEW

**Comment by zth** [comment]
I like this in general! But, I worry about perf. Does this mean that the cmt is processed for every file module that can be found? If so, it's important to test the cases where we complete and get tons of file modules back. Like when completing for "nothing" at the top level for example.

Could you bench this somehow? Preferably in a larger project. We could for example consider doing the lookups for only the first X file modules, and do them lazily as needed.

**Comment by zth** [comment]
@aspeddro could we check the perf here somehow?

**Comment by aspeddro** [comment]
I'll check this week

**Comment by aspeddro** [comment]
I changed it to draft bc the implementation is wrong

**Pull request closed without merging**
